export const FETCH_PHOTOS = 'FETCH_PHOTOS'
export const TOGGLE_BOOKED = 'TOGGLE_BOOKED'
export const REQUEST_PHOTOS = 'REQUEST_PHOTOS'
export const DELETE_PHOTO = 'DELETE_PHOTO'

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
export const SHOW_ALERT = 'SHOW_ALERT'